### ISSUE TITLE
Support for custom-folder like structures

### ISSUE THREAD

**Issue by Kolky** [AnyStatus/API#2]
While trying to create "multibranch" support for Jenkins (https://github.com/AnyStatus/Plugins/pull/4), I wanted to create a folder like structure. However when adding sub-items to a build it does nothing in the UI, although it works for the configuration files.

Would be nice to have proper support for this!

Another way would be by releasing the source of the extension, so I can fix it myself.

**Comment by AlonAm** [comment]
Very nice idea,
I'll review and commit the changes asap
thank you

**Comment by AlonAm** [comment]
All tree view items in the dashboard support child items (plugins, folders, etc.).
But the rest of the application supports only folders at the moment. 
The way you implemented the new plugin is very interesting as it adds new items in runtime, which I haven't thought about myself. Let me give this some thought to see how it can be supported in the API...

**Comment by AlonAm** [comment]
You can use this standalone version of AnyStatus to test plugins.
Note, the .msi is not yet signed. if you have anti-virus software installed, it will show some warnings, you can ignore those.

**Comment by AlonAm** [comment]
I have tested your plugin using this job I found in the wild: https://jenkins.qa.ubuntu.com/view/Precise/view/ISO%20Testing%20Dashboard/
not sure it's suitable for the tests, let me know otherwise.

Why did you chose to add the jobs to the parent and not the multi-branch plugin?

**Comment by Kolky** [comment]
Then it does not update the UI for some reason, although, I might have not tested it enough yet ;)

**Comment by AlonAm** [comment]
If you could add child items to the plugin itself, would you prefer to do
that?

**Comment by Kolky** [comment]
That is certainly a good option, and I think allowing anyone to create sub-items to be helpful. Although there has to be a limitation on how many levels deep it could go!

Another option might be to allow for a Jenkins MultiBranch item to be at the level of a Folder.

**Comment by AlonAm** [comment]
support has been added in 1.3.97

**Comment by AlonAm** [comment]
The multi-branch plugin now works, tested with URL:  https://jenkins.qa.ubuntu.com/view/Precise/view/ISO%20Testing%20Dashboard/

![image](https://user-images.githubusercontent.com/3127610/29721269-3273d5ce-89c5-11e7-8363-5d1bfb141ff5.png)

**Comment by AlonAm** [comment]
https://github.com/AnyStatus/Support/issues/24
